### ISSUE TITLE
filter out recent days?

### ISSUE THREAD

**Issue by smwindecker** [infectious-disease-ecology-modelling/GPreff#2]
possibly want to be able to filter recent days out of the delay distribution functions

**Comment by AugustHao** [comment]
see this paper appendix A for a similar approach/justification: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-023-05428-4#appendices

in summary, because not all recent infections had been observed yet in the latest reported cases, those that would have been observed would have shorter delays than average. So if we had observed these shorter delays, and computed time varying delays following these observations, then we would erroneously underestimate delay for the most recent time period. Thus we should ignore information about delay in the most recent days and clamp delay distribution as constant at about 1 max delay range from the present, as they have done in the paper
